spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

langchain4j:
  open-ai:
    chat-model:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: "https://api.deepseek.com"
      model-name: "deepseek-chat"
      log-requests: false
      log-responses: false
  ollama:
    embedding-model:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      model-name: ${OLLAMA_EMBEDDING_MODEL:bge-m3}
      log-responses: false
      timeout: 30s
jwt:
  secret: ${JWT_SECRET}
  expiration: 604800
  tokenHead: 'Bearer '

logging:
  level:
    com.example.demo: INFO