server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 121311
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

#mybatis-plus:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

langchain4j:
  open-ai:
    chat-model:
      api-key: "sk-49412e1232c54ba8b8a40c854b3edf21"
      base-url: "https://api.deepseek.com"
      model-name: "deepseek-chat"
      log-requests: true
      log-responses: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头