package com.example.demo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.example.demo.model.entity.OmsOrder;
import com.example.demo.model.entity.OmsOrderExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OmsOrderMapper extends BaseMapper<OmsOrder> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    long countByExample(OmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int deleteByExample(OmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int insert(OmsOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int insertSelective(OmsOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    List<OmsOrder> selectByExample(OmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    OmsOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByExampleSelective(@Param("row") OmsOrder row, @Param("example") OmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByExample(@Param("row") OmsOrder row, @Param("example") OmsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByPrimaryKeySelective(OmsOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByPrimaryKey(OmsOrder row);
}