package com.example.demo.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.example.demo.model.entity.PmsProduct;
import com.example.demo.model.entity.PmsProductExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PmsProductMapper extends BaseMapper<PmsProduct> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    long countByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int deleteByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int insert(PmsProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int insertSelective(PmsProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    List<PmsProduct> selectByExampleWithBLOBs(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    List<PmsProduct> selectByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    PmsProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByExampleSelective(@Param("row") PmsProduct row, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") PmsProduct row, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByExample(@Param("row") PmsProduct row, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByPrimaryKeySelective(PmsProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(PmsProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    int updateByPrimaryKey(PmsProduct row);
}