package com.example.demo.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName("ai_conversation")
public class AiConversation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_conversation.id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_conversation.user_id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_conversation.title
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_conversation.thread_id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_conversation.status
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_conversation.create_time
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_conversation.update_time
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ai_conversation
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private static final long serialVersionUID = 1L;
}