package com.example.demo.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AiMessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public AiMessageExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andConversationIdIsNull() {
            addCriterion("conversation_id is null");
            return (Criteria) this;
        }

        public Criteria andConversationIdIsNotNull() {
            addCriterion("conversation_id is not null");
            return (Criteria) this;
        }

        public Criteria andConversationIdEqualTo(Long value) {
            addCriterion("conversation_id =", value, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdNotEqualTo(Long value) {
            addCriterion("conversation_id <>", value, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdGreaterThan(Long value) {
            addCriterion("conversation_id >", value, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("conversation_id >=", value, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdLessThan(Long value) {
            addCriterion("conversation_id <", value, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdLessThanOrEqualTo(Long value) {
            addCriterion("conversation_id <=", value, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdIn(List<Long> values) {
            addCriterion("conversation_id in", values, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdNotIn(List<Long> values) {
            addCriterion("conversation_id not in", values, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdBetween(Long value1, Long value2) {
            addCriterion("conversation_id between", value1, value2, "conversationId");
            return (Criteria) this;
        }

        public Criteria andConversationIdNotBetween(Long value1, Long value2) {
            addCriterion("conversation_id not between", value1, value2, "conversationId");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(String value) {
            addCriterion("role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(String value) {
            addCriterion("role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(String value) {
            addCriterion("role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(String value) {
            addCriterion("role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(String value) {
            addCriterion("role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(String value) {
            addCriterion("role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLike(String value) {
            addCriterion("role like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotLike(String value) {
            addCriterion("role not like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<String> values) {
            addCriterion("role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<String> values) {
            addCriterion("role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(String value1, String value2) {
            addCriterion("role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(String value1, String value2) {
            addCriterion("role not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andToolNameIsNull() {
            addCriterion("tool_name is null");
            return (Criteria) this;
        }

        public Criteria andToolNameIsNotNull() {
            addCriterion("tool_name is not null");
            return (Criteria) this;
        }

        public Criteria andToolNameEqualTo(String value) {
            addCriterion("tool_name =", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameNotEqualTo(String value) {
            addCriterion("tool_name <>", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameGreaterThan(String value) {
            addCriterion("tool_name >", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameGreaterThanOrEqualTo(String value) {
            addCriterion("tool_name >=", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameLessThan(String value) {
            addCriterion("tool_name <", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameLessThanOrEqualTo(String value) {
            addCriterion("tool_name <=", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameLike(String value) {
            addCriterion("tool_name like", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameNotLike(String value) {
            addCriterion("tool_name not like", value, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameIn(List<String> values) {
            addCriterion("tool_name in", values, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameNotIn(List<String> values) {
            addCriterion("tool_name not in", values, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameBetween(String value1, String value2) {
            addCriterion("tool_name between", value1, value2, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolNameNotBetween(String value1, String value2) {
            addCriterion("tool_name not between", value1, value2, "toolName");
            return (Criteria) this;
        }

        public Criteria andToolCallIdIsNull() {
            addCriterion("tool_call_id is null");
            return (Criteria) this;
        }

        public Criteria andToolCallIdIsNotNull() {
            addCriterion("tool_call_id is not null");
            return (Criteria) this;
        }

        public Criteria andToolCallIdEqualTo(String value) {
            addCriterion("tool_call_id =", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdNotEqualTo(String value) {
            addCriterion("tool_call_id <>", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdGreaterThan(String value) {
            addCriterion("tool_call_id >", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdGreaterThanOrEqualTo(String value) {
            addCriterion("tool_call_id >=", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdLessThan(String value) {
            addCriterion("tool_call_id <", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdLessThanOrEqualTo(String value) {
            addCriterion("tool_call_id <=", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdLike(String value) {
            addCriterion("tool_call_id like", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdNotLike(String value) {
            addCriterion("tool_call_id not like", value, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdIn(List<String> values) {
            addCriterion("tool_call_id in", values, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdNotIn(List<String> values) {
            addCriterion("tool_call_id not in", values, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdBetween(String value1, String value2) {
            addCriterion("tool_call_id between", value1, value2, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andToolCallIdNotBetween(String value1, String value2) {
            addCriterion("tool_call_id not between", value1, value2, "toolCallId");
            return (Criteria) this;
        }

        public Criteria andPromptTokensIsNull() {
            addCriterion("prompt_tokens is null");
            return (Criteria) this;
        }

        public Criteria andPromptTokensIsNotNull() {
            addCriterion("prompt_tokens is not null");
            return (Criteria) this;
        }

        public Criteria andPromptTokensEqualTo(Integer value) {
            addCriterion("prompt_tokens =", value, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensNotEqualTo(Integer value) {
            addCriterion("prompt_tokens <>", value, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensGreaterThan(Integer value) {
            addCriterion("prompt_tokens >", value, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensGreaterThanOrEqualTo(Integer value) {
            addCriterion("prompt_tokens >=", value, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensLessThan(Integer value) {
            addCriterion("prompt_tokens <", value, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensLessThanOrEqualTo(Integer value) {
            addCriterion("prompt_tokens <=", value, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensIn(List<Integer> values) {
            addCriterion("prompt_tokens in", values, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensNotIn(List<Integer> values) {
            addCriterion("prompt_tokens not in", values, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensBetween(Integer value1, Integer value2) {
            addCriterion("prompt_tokens between", value1, value2, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andPromptTokensNotBetween(Integer value1, Integer value2) {
            addCriterion("prompt_tokens not between", value1, value2, "promptTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensIsNull() {
            addCriterion("completion_tokens is null");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensIsNotNull() {
            addCriterion("completion_tokens is not null");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensEqualTo(Integer value) {
            addCriterion("completion_tokens =", value, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensNotEqualTo(Integer value) {
            addCriterion("completion_tokens <>", value, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensGreaterThan(Integer value) {
            addCriterion("completion_tokens >", value, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensGreaterThanOrEqualTo(Integer value) {
            addCriterion("completion_tokens >=", value, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensLessThan(Integer value) {
            addCriterion("completion_tokens <", value, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensLessThanOrEqualTo(Integer value) {
            addCriterion("completion_tokens <=", value, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensIn(List<Integer> values) {
            addCriterion("completion_tokens in", values, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensNotIn(List<Integer> values) {
            addCriterion("completion_tokens not in", values, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensBetween(Integer value1, Integer value2) {
            addCriterion("completion_tokens between", value1, value2, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andCompletionTokensNotBetween(Integer value1, Integer value2) {
            addCriterion("completion_tokens not between", value1, value2, "completionTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensIsNull() {
            addCriterion("total_tokens is null");
            return (Criteria) this;
        }

        public Criteria andTotalTokensIsNotNull() {
            addCriterion("total_tokens is not null");
            return (Criteria) this;
        }

        public Criteria andTotalTokensEqualTo(Integer value) {
            addCriterion("total_tokens =", value, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensNotEqualTo(Integer value) {
            addCriterion("total_tokens <>", value, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensGreaterThan(Integer value) {
            addCriterion("total_tokens >", value, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_tokens >=", value, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensLessThan(Integer value) {
            addCriterion("total_tokens <", value, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensLessThanOrEqualTo(Integer value) {
            addCriterion("total_tokens <=", value, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensIn(List<Integer> values) {
            addCriterion("total_tokens in", values, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensNotIn(List<Integer> values) {
            addCriterion("total_tokens not in", values, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensBetween(Integer value1, Integer value2) {
            addCriterion("total_tokens between", value1, value2, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andTotalTokensNotBetween(Integer value1, Integer value2) {
            addCriterion("total_tokens not between", value1, value2, "totalTokens");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ai_message
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 26 14:41:53 CST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}