package com.example.demo.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName("ai_message")
public class AiMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.conversation_id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Long conversationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.role
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.tool_name
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String toolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.tool_call_id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String toolCallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.prompt_tokens
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Integer promptTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.completion_tokens
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Integer completionTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.total_tokens
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Integer totalTokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.create_time
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.content
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_message.tool_calls
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String toolCalls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ai_message
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private static final long serialVersionUID = 1L;
}