package com.example.demo.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName("ai_tool_log")
public class AiToolLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.message_id
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Long messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.tool_name
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String toolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.success
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Byte success;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.error_msg
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String errorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.execute_time_ms
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Integer executeTimeMs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.create_time
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.request_params
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String requestParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ai_tool_log.response_data
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private String responseData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ai_tool_log
     *
     * @mbg.generated Sun Apr 26 14:41:53 CST 2026
     */
    private static final long serialVersionUID = 1L;
}