package com.example.demo.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;

@Data
@TableName("oms_order_item")
public class OmsOrderItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    @TableId(type= IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.order_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.order_sn
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_pic
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_name
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_brand
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_sn
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_price
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_quantity
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_sku_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long productSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_sku_code
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productSkuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_category_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.promotion_name
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String promotionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.promotion_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal promotionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.coupon_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal couponAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.integration_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal integrationAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.real_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal realAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.gift_integration
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer giftIntegration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.gift_growth
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer giftGrowth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_attr
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order_item
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private static final long serialVersionUID = 1L;
}