package com.example.demo.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.sun.jdi.Type;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
@TableName("oms_order")
public class OmsOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    @TableId(type= IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.member_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.coupon_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_sn
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.create_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.member_username
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String memberUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.total_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.freight_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal freightAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.promotion_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal promotionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.integration_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal integrationAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.coupon_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal couponAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.discount_amount
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_type
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.source_type
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_type
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_company
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String deliveryCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_sn
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String deliverySn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.auto_confirm_day
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer autoConfirmDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.integration
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer integration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.growth
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer growth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.promotion_info
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String promotionInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_type
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer billType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_header
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String billHeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_content
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String billContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_receiver_phone
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String billReceiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_receiver_email
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String billReceiverEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_name
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_phone
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_post_code
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String receiverPostCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_province
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String receiverProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_city
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_region
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String receiverRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_detail_address
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String receiverDetailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.note
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.confirm_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer confirmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delete_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.use_integration
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer useIntegration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.payment_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receive_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.comment_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.modify_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private static final long serialVersionUID = 1L;
}