package com.example.demo.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
@TableName("pms_product")
public class PmsProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.brand_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_category_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.feight_template_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long feightTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_attribute_category_id
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Long productAttributeCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.name
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.pic
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_sn
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.delete_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.publish_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer publishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.new_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer newStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.recommand_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer recommandStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.verify_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer verifyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.sort
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.sale
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.price
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_price
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal promotionPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.gift_growth
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer giftGrowth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.gift_point
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer giftPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.use_point_limit
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer usePointLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.sub_title
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.original_price
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.stock
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.low_stock
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer lowStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.unit
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.weight
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.preview_status
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer previewStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.service_ids
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String serviceIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.keywords
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.note
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.album_pics
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String albumPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_title
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String detailTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_start_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date promotionStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_end_time
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Date promotionEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_per_limit
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer promotionPerLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.promotion_type
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private Integer promotionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.brand_name
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.product_category_name
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String productCategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.description
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_desc
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String detailDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_html
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String detailHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product.detail_mobile_html
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private String detailMobileHtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product
     *
     * @mbg.generated Sun Apr 26 18:38:09 CST 2026
     */
    private static final long serialVersionUID = 1L;

}