package com.example.demo.model.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName("ums_admin")
public class UmsAdmin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.id
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.username
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.password
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.icon
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.email
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.nick_name
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.note
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.create_time
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.login_time
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin.status
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_admin
     *
     * @mbg.generated Tue Apr 28 08:25:21 CST 2026
     */
    private static final long serialVersionUID = 1L;
}